# 1-2 skapa gles matris

In [23]:
import pandas as pd
import numpy as np

In [24]:
ratings_raw = pd.read_csv('./data/ratings_big.csv', dtype={'userId': 'int32', 'movieId': 'int32', 'rating':'float16', 'timestamp': 'int32'}).drop('timestamp', axis=1)
ratings_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27753444 entries, 0 to 27753443
Data columns (total 3 columns):
 #   Column   Dtype  
---  ------   -----  
 0   userId   int32  
 1   movieId  int32  
 2   rating   float16
dtypes: float16(1), int32(2)
memory usage: 264.7 MB


In [25]:
all_movieId = ratings_raw['movieId'].unique()
all_userId = ratings_raw['userId'].unique()

all_movieId, all_userId

(array([   307,    481,   1091, ..., 117857, 133409, 142855], dtype=int32),
 array([     1,      2,      3, ..., 283226, 283227, 283228], dtype=int32))

In [26]:
movieId_df = pd.DataFrame(all_movieId)
userId_df = pd.DataFrame(all_userId)
movieId_df.head(), userId_df.head()

(      0
 0   307
 1   481
 2  1091
 3  1257
 4  1449,
    0
 0  1
 1  2
 2  3
 3  4
 4  5)

In [27]:
movieId_dict = movieId_df.to_dict()[0]
dict(zip(movieId_dict.values(), movieId_dict.keys()))[307],dict(zip(movieId_dict.values(), movieId_dict.keys()))[481]

(0, 1)

In [28]:
def create_id_and_csr_index_dictionary(data_frame: pd.DataFrame, column: str) -> dict:
    unique_id_dict = pd.DataFrame(data_frame[column].unique()).to_dict()[0]
    return dict(zip(unique_id_dict.values(), unique_id_dict.keys()))

movieId_dict = create_id_and_csr_index_dictionary(ratings_raw, 'movieId')
userId_dict = create_id_and_csr_index_dictionary(ratings_raw, 'userId')

In [29]:
ratings_raw.columns

Index(['userId', 'movieId', 'rating'], dtype='object')

In [30]:
ratings_row_lists = []
for rows in ratings_raw.itertuples():
    ratings_row_lists.append([rows.userId, rows.movieId, rows.rating])
ratings_row_lists[:5]

[[1, 307, 3.5], [1, 481, 3.5], [1, 1091, 1.5], [1, 1257, 4.5], [1, 1449, 4.5]]

In [31]:
len(ratings_row_lists)

27753444

In [32]:
converted_into_rows_and_columns_list = []
for item in ratings_row_lists:
    converted_into_rows_and_columns_list.append([userId_dict[item[0]], movieId_dict[item[1]], item[2]])
converted_into_rows_and_columns_list[:5]

[[0, 0, 3.5], [0, 1, 3.5], [0, 2, 1.5], [0, 3, 4.5], [0, 4, 4.5]]

In [33]:
column = np.array([item[0] for item in converted_into_rows_and_columns_list])
row = np.array([item[1] for item in converted_into_rows_and_columns_list])
data = np.array([item[2] for item in converted_into_rows_and_columns_list])
column[:5], row[:5], data[:5]

(array([0, 0, 0, 0, 0]),
 array([0, 1, 2, 3, 4]),
 array([3.5, 3.5, 1.5, 4.5, 4.5]))

In [34]:
len(all_movieId), len(all_userId)

(53889, 283228)

In [35]:
from scipy.sparse import csr_matrix
ratings_csr_matrix = csr_matrix((data, (row, column)), shape=(53889, 283228))
print(ratings_csr_matrix)

  (0, 0)	3.5
  (0, 5)	4.0
  (0, 55)	4.0
  (0, 70)	5.0
  (0, 83)	3.0
  (0, 140)	5.0
  (0, 212)	4.0
  (0, 213)	4.0
  (0, 238)	4.0
  (0, 267)	4.0
  (0, 276)	3.0
  (0, 333)	4.0
  (0, 334)	4.0
  (0, 359)	4.0
  (0, 364)	5.0
  (0, 398)	3.0
  (0, 407)	2.0
  (0, 414)	5.0
  (0, 427)	4.0
  (0, 462)	3.0
  (0, 494)	2.5
  (0, 496)	4.0
  (0, 548)	5.0
  (0, 565)	4.0
  (0, 567)	5.0
  :	:
  (53864, 282118)	3.5
  (53865, 282118)	2.5
  (53866, 282118)	3.0
  (53867, 282118)	3.0
  (53868, 282118)	3.0
  (53869, 282118)	3.0
  (53870, 282118)	3.5
  (53871, 282118)	3.0
  (53872, 282118)	3.0
  (53873, 282118)	3.5
  (53874, 282373)	2.5
  (53875, 282373)	4.0
  (53876, 282373)	1.5
  (53877, 282373)	3.0
  (53878, 282373)	3.5
  (53879, 282373)	3.0
  (53880, 282373)	4.0
  (53881, 282373)	4.0
  (53882, 282373)	2.5
  (53883, 282373)	4.5
  (53884, 282402)	1.0
  (53885, 282731)	3.5
  (53886, 282999)	3.5
  (53887, 282999)	3.5
  (53888, 282999)	3.5
